@server = http://localhost:8091/api

@instrumentos = {{server}}/instrumentos

@musicos = {{server}}/musicos

@integrantes = {{server}}/integrantes
###

GET {{instrumentos}}

###

GET {{musicos}}/1

###

POST {{instrumentos}}
Content-Type: application/json

{"nombre": "Quena", "categoria": "Instrumento de viento", "descripcion": "tubo con orificios que al taparlos hacen sonr diferentes notas"}

###

GET {{server}}/bandas/1/formacion