@server = http://localhost:8091/api

@instrumentos = {{server}}/instrumentos

@musicos = {{server}}/musicos
###

GET {{instrumentos}}

###

GET {{musicos}}

###

POST {{instrumentos}}
Content-Type: application/json

{"nombre": "Quena", "categoria": "Instrumento de viento", "descripcion": "tubo con orificios que al taparlos hacen sonr diferentes notas"}